window:
  opacity: 0.34
  dimensions:
    columns: 75
    lines: 24

cursor:
  style:
    shape: Beam
    blinking: On

font:
  normal:
    family: Lucida Console
  size: 12

colors:
  primary:
    background: '#020B0E'
    foreground: '#FFFFFF'
  normal:
    black:   '#171421'
    red:     '#C01C28'
    green:   '#26A269'
    yellow:  '#A2734C'
    blue:    '#12488B'
    magenta: '#A347BA'
    cyan:    '#2AA1B3'
    white:   '#D0CFCC'
  bright:
    black:   '#5E5C64'
    red:     '#F66151'
    green:   '#33D17A'
    yellow:  '#E9AD0C'
    blue:    '#2A7BDE'
    magenta: '#C061CB'
    cyan:    '#33C7DE'
    white:   '#FFFFFF'

key_bindings:
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: V, mods: Control,       action: Paste }
  - { key: N, mods: Control,       action: SpawnNewInstance }
  # - { key: T, mods: Control,       action: CreateNewWindow }




