#!/usr/bin/env python3
import os; print('"' + '" "'.join(sorted(  [i for i in os.listdir() if (not i.startswith('.')) and i.endswith('.pdf') and ')' in i and i]  ,  key=lambda x: int(x[:x.index(')')])  )) + '"', end='')
