swipe:
  3:
    left:
      command: "xdotool key super+Right" # History forward
    right:
      command: "xdotool key super+Left" # History back
    up:
      command: "xmessage test" # Activity

threshold:
  swipe: 0.25
interval:
  swipe: 0.5
