swipe:
  3:
    left:
      command: "xdotool key super+Right" # Right workspace
    right:
      command: "xdotool key super+Left" # Left workspace
    up:
      command: "skippy-xd --toggle-window-picker" # Skippy xd
      threshold: 0.25
    down:
      command: "skippy-xd --toggle-window-picker" # Skippy xd
      threshold: 0.25



threshold:
  swipe: 0.5
